# Generated by Django 2.2.12 on 2020-05-09 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='dicount',
            new_name='discount',
        ),
    ]
